name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows to run workflow manually from Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and update Hugo themes
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.144.1"
          extended: true

      - name: Set API Keys in config
        run: |
          sed -i "s/arliaiApiKey = \"\"/arliaiApiKey = \"${{ secrets.ARLIAI_API_KEY }}\"/" config.toml
          sed -i "s/googleAnalytics = \"\"/googleAnalytics = \"${{ secrets.GOOGLE_ANALYTICS_ID }}\"/" config.toml

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
